- name: Ensure jenkins namespace exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: jenkins

- name: Create jenkins-admin serviceaccount
  kubernetes.core.k8s:
    api_version: v1
    kind: ServiceAccount
    name: jenkins-admin
    namespace: jenkins

- name: Create clusterrolebinding for jenkins-admin
  kubernetes.core.k8s:
    api_version: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    name: jenkins-admin-binding
    role_ref:
      kind: ClusterRole
      name: cluster-admin
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: jenkins-admin
        namespace: jenkins

- name: Create persistent token secret for jenkins-admin
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: jenkins-admin-token
        namespace: jenkins
        annotations:
          kubernetes.io/service-account.name: "jenkins-admin"
      type: kubernetes.io/service-account-token

- name: Get Jenkins token from secret
  command: >
    kubectl -n jenkins get secret jenkins-admin-token
    -o jsonpath='{.data.token}'
  register: jenkins_token

- name: Show Jenkins token
  debug:
    msg: "Jenkins persistent token is {{ jenkins_token.stdout | b64decode }}"