- name: Ensure namespace jenkins exists
  ansible.builtin.command:
    cmd: kubectl create namespace jenkins

- name: Create jenkins-admin serviceaccount
  ansible.builtin.command:
    cmd: kubectl create serviceaccount jenkins-admin -n jenkins

- name: Create clusterrolebinding for jenkins-admin
  command:
    argv:
      - kubectl
      - create
      - clusterrolebinding
      - jenkins-admin-binding
      - --clusterrole=cluster-admin
      - --serviceaccount=jenkins:jenkins-admin

- name: Create token for jenkins-admin
  ansible.builtin.command:
    cmd: kubectl create token jenkins-admin -n jenkins
  register: jenkins_token

- name: Show Jenkins token
  ansible.builtin.debug:
    msg: "Jenkins token is {{ jenkins_token.stdout }}"